
#Setup  page
APP_SETUP_TITLE = "appSetup"
AGENT_COMMISSION_SETUP_TITLE = "agentCommissionSetup"
#User Rolls
ROLL_PASSENGER = "passenger"
ROLL_OWNER = "owner"
ROLL_DRIVER = "driver"
#Refference Type
REFFERENCE_TYPE_OWNER = "byOwner"
REFFERENCE_TYPE_DRIVER = "byDriver"
REFFERENCE_TYPE_ADMIN = "byAdmin"
#Service Types
SERVICE_RENTAL = "rental"
SERVICE_LEASE = "lease"
SERVICE_RIDESHARE = "rideshare"
SERVICE_INSTANTRIDE = "instantride"
#Status
STATUS_PENDING = 'pending'
STATUS_VERIFIED = 'verified'
STATUS_REJECTED = 'rejected'
#Vehicle Category by Driving Licence
VEHICLE_CATEGORY_TYPE_HEAVY_VALUE = 1
VEHICLE_CATEGORY_TYPE_MEDIUM_VALUE = 2
VEHICLE_CATEGORY_TYPE_LIGHT_VALUE = 3
VEHICLE_CATEGORY_TYPE_MOTORCYCLE_VALUE = 4
VEHICLE_CATEGORY_TYPE_THREE_WHEELERS_VALUE = 5
VEHICLE_CATEGORY_TYPE_THREE_PSV = 6
VEHICLE_CATEGORY_TYPE_THREE_OTHER = 7
#Agent Commission Setup
